[assembly: System.Reflection.AssemblyTitle("DjToKey")]
[assembly: System.Reflection.AssemblyDescription("DjToKey")]
[assembly: System.Reflection.AssemblyCompany("Marcin Badurowicz")]
[assembly: System.Reflection.AssemblyProduct("DjToKey")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Marcin Badurowicz 2015")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]

[assembly: System.Reflection.AssemblyVersion("${GfvSemVer}")]
[assembly: System.Reflection.AssemblyFileVersion("${GfvAssemblySemVer}")]
[assembly: System.Reflection.AssemblyInformationalVersion("${GfvFullSemVer}.${GfvBranchName}.${ShortSha}")]