version: 0.4.0+{build}

branches:
  only:
  - master

platform: x86
  
configuration: Release

before_build:
- nuget restore

build:
  project: DjToKey.sln
  verbosity: minimal

after_build:
- 7z a djtokey.zip %APPVEYOR_BUILD_FOLDER%\DjToKey\bin\x86\Release\DjToKey.exe*  %APPVEYOR_BUILD_FOLDER%\DjToKey\bin\x86\Release\Devices  %APPVEYOR_BUILD_FOLDER%\DjToKey\bin\x86\Release\*.dll %APPVEYOR_BUILD_FOLDER%\DjToKey\bin\x86\Release\pl-PL

artifacts:
- path: djtokey.zip
  name: App

deploy:
- provider: GitHub
  auth_token:
    secure: X6ZxqNgcaXUuh5f1BuwA792oqE7Ha+8AtoyVra4IitrjuiBxb28NCLJ1s9PRCrYa

  artifact: App
  draft: true

  on:
    branch: master